config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 20 }
  validates :height, presence: true, length: { maximum: 3 }
  validates :weight, presence: true, length: { maximum: 3 }
  validates :complications, presence: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid name/password combination' 
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.all
  end
  
  
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.all
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
   def user_params
     params.require(:user).permit(:name, :password, :password_confirmation,
                                  :height, :weight, :complications, )
   end
   
   def logged_in_user
     unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
     end
   end
   
   def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
     session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
   <%= link_to "トップページへ戻る" , root_path %>
  </nav> 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
          <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> </title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> </title>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div style="text-align:center">
  <h1>新肥満度判定</h1>

  <h2>
    BMIに加えて、肥満の時に発生する合併症の有無で診断
  </h2>

  <%= link_to "診断", signup_path , class: "btn-success btn-lg" %>
  
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h4>診断結果一覧</h4>

<ul class="users">
 <ul style="list-style-type: none ">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>&nbsp;&nbsp;&nbsp;
      
      <%= link_to "削除", user, method: :delete, data: { confirm: "削除しますか?" } %>
    </li>
  <% end %>
 </ul>  
</ul>

app/views/users/new.html.erb
<%provide(:title, 'Sing up')%>
<h1>ACCE/ACEの肥満度判定</h1>

<div style="text-align:center">
 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.label :身長（cm） %>
      <%= f.number_field :height, {:class => 'form-control', :min => "0"} %>

      <%= f.label :体重（kg） %>
      <%= f.number_field :weight, {:class => 'form-control', :min => "0"} %>
      
       <%= f.label "合併症（高血圧、高脂血症、腰痛）の有無" %><br>
       <label class="radio-inline">
        <%= f.radio_button :complications, 1, {:class => 'form-control'} %>なし 
       </label>
       <label class="radio-inline">
        <%= f.radio_button :complications, 2, {:class => 'form-control'} %>軽い合併症がある
       </label>
       <label class="radio-inline">
        <%= f.radio_button :complications, 3, {:class => 'form-control'} %>重い合併症がある
       </label>
      
      <%= f.submit "診断", class: "btn-success btn-lg" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h4>診断結果</h4>

<div class="row">
  <aside class="col-md-4">
   
    <section>
     
       <h2>
        <%= @user.name %><br><br>
        
        <% bmi = @user.weight/(@user.height/100.0)**2 %>
        BMI <%= bmi.round(1) %><br><br>
        
        <% if bmi < 18.5 then%>
         低体重
        <% elsif bmi >= 18.5 && bmi < 25.0  then%>
         標準体重
        <% elsif bmi >= 25.0 && bmi < 29.9 && @user.complications==1 then%>
         過体重
        <% elsif bmi >= 30.0 && @user.complications==1 then%>
         肥満ステージ０
        <% elsif bmi >= 25.0 && @user.complications==2 then%>
         肥満ステージ１
        <% elsif bmi >= 25.0 && @user.complications==3 then%>
         肥満ステージ２
        <% else %>
         測定不可
        <% end %>
    　 </h2>
    　 
    　 <h3>
    　  1.低体重(BMIが18.5未満)<br>
    　  2.標準体重(BMIが18.5～25未満)<br>
    　  3.過体重(BMIが25～29.9で合併症がない)<br>
    　  4.肥満ステージ０(BMIが30以上で、合併症がない)<br>
    　  5.肥満ステージ１(BMIが25以上で、軽い合併症がある)<br>
    　  6.肥満ステージ２(BMIが25以上で、重い合併症がある)<br>
    　  5と6はBMIが低くても、より危険
    　 </h3>
    　 
    </section>
  </aside>
</div>